### ISSUE TITLE
gamma.context.ContextError: Unable to set gamma ramp; has the gamma range been unlocked yet?

### ISSUE THREAD

**Issue by Q3X8** [dev7355608/csgo_dont_blind_me#12]
I think this started happening when I updated to Win 11 22H2. 
Inside of
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM
I have a DWORD named GdiIcmGammaRange with a hex value of 100

That's right, right? Here's the full error in CMD.

Error handling request
Traceback (most recent call last):
  File "aiohttp\web_protocol.py", line 422, in _handle_request
  File "aiohttp\web_app.py", line 499, in _handle
  File "app.py", line 167, in handle
  File "app.py", line 223, in update_brightness
  File "gamma\context_wingdi.py", line 168, in set_ramp
gamma.context.ContextError: Unable to set gamma ramp; has the gamma range been unlocked yet?

This error appears any time I see a flash.

BTW thank you for making this :)

**Comment by dev7355608** [comment]
The update may have relocked the gamme ramp. Run `unlock_gamma_range.reg` again.

**Comment by Q3X8** [comment]
I did, it still has that same error.

**Comment by dev7355608** [comment]
I assume you already made sure all monitors except the primary are off?

> 5. If you have multiple monitors configured with `Extend these displays`,
   you might need to turn off all but the primary monitor. (Windows only)

**Comment by Q3X8** [comment]
That is correct, I even disconnected my second monitor from my GPU and tested again, still the same error.  Using version 0.5.2 btw

**Comment by Q3X8** [comment]
I just updated my NVidia drivers from the July or August 2022 drivers to the September one, rebooted, and it's working great. I did "perform a clean install," Not sure where the issue came from, if you want me to upload anything let me know. Appreciate the help and software!
