### ISSUE TITLE
[WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by upbox-org** [dev7355608/csgo_dont_blind_me#4]
Hi,

I've followed the instructions carefully, but after registering the reg-file and restarting, the program only gives me this output:
```
OSError: [WinError 87] The parameter is incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 264, in <module>
  File "app.py", line 201, in adjust_brightness
  File "gamma\gamma_wingdi.py", line 125, in set
RuntimeError: Unable to set gamma ramp
Failed to execute script app
Error in atexit._run_exitfuncs:
OSError: [WinError 87] The parameter is incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "contextlib.py", line 77, in __exit__
  File "gamma\gamma_wingdi.py", line 83, in get_dc
  File "gamma\gamma_wingdi.py", line 135, in set_default
RuntimeError: Unable to set gamma ramp
```
OS: Windows 10 (x64)

**Comment by dev7355608** [comment]
Are these all errors? Do you have multiple monitors?

**Comment by upbox-org** [comment]
Yes, I've connected a second monitor. 
The primary monitor becomes brighter for a short time and then the error message appear. 
Thats all and nothing happens ingame.

**Comment by dev7355608** [comment]
Do the errors appear when you throw the first flash or shortly after you start the app?

**Comment by upbox-org** [comment]
After starting the app.

**Comment by dev7355608** [comment]
Could you post the complete output of the app?

**Comment by dev7355608** [comment]
And only your primary monitor gets brighter for a short time and the second monitor stays the same?

**Comment by upbox-org** [comment]
```
PLEASE READ THE INSTRUCTIONS CAREFULLY!

Don't forget to copy gamestate_integration_dont_blind_me.cfg into
    ...\Steam\userdata\________\730\local\cfg, or
    ...\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg!

Don't forget to set your preferred gamma in settings.json! Currently set to:
    mat_monitorgamma             1.60
    mat_monitorgamma_tv_enabled  0

Don't forget to set the launch option -nogammaramp!

Don't forget to disable f.lux!
Don't forget to disable Redshift!
Don't forget to disable Windows Night Light!
Don't forget to disable Xbox DVR/Game bar!

In case you get an error:
    Did you restart your PC after running set_max_gamma_range.reg?

OSError: [WinError 87] The parameter is incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 264, in <module>
  File "app.py", line 201, in adjust_brightness
  File "gamma\gamma_wingdi.py", line 125, in set
RuntimeError: Unable to set gamma ramp
Failed to execute script app
Error in atexit._run_exitfuncs:
OSError: [WinError 87] The parameter is incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "contextlib.py", line 77, in __exit__
  File "gamma\gamma_wingdi.py", line 83, in get_dc
  File "gamma\gamma_wingdi.py", line 135, in set_default
RuntimeError: Unable to set gamma ramp


Press CTRL+C to quit...
```
Thats the complete output.
Only the the primary monitor gets brighter and it's just for a very short time.

**Comment by alqy** [comment]
I was getting that same error. It started when i ran set_max_gamma_range.reg. Try running restore_gamma_range.reg. This helped me get rid of those errors but i still havent gotten the program to run properly.

**Comment by dev7355608** [comment]
Weird errors. Please try v0.3.2.1 (31d383858891b5d505cdeb366150aa8382e77df6).

**Comment by Garry050** [comment]
me too. and 0.3.2.1 doesn't help me...

Windows 8.1 x64
Primary Minitor: connecting GTX 1050Ti
Secondary Monitor: connecting Intel HD Graphics 4600(CPU Graphics) 

i will try uninstall Intel Graphics, and secondary monitor connect GTX 750Ti

<img src=https://storage.ppn.pw/cc/img/645ca6c4/t685d4eb3.png>

**Comment by Garry050** [comment]
If we have 2 or more graphics card, will be get WinError 87.

Workaround: **Disable** (or disconnect) sub graphics card.

sorry my english

**Comment by dev7355608** [comment]
Please let me know if the error disappears if you turn of your secondary monitor. Also please try the following and let me know if it resolves the problem:

1. If you have a Nvidia graphics card, go into *Nvidia Control Panel* ->*3D Settings* -> *Manage 3D Settings* and set *Preferred graphics processor* to  *High-performance NVIDIA processor*.
2. Try disabling the integrated graphic card: go to *Device Manager* -> *Display adapters* and disable everything except your dedicated graphics card.

**Comment by dev7355608** [comment]
Also please try v0.3.2.2 (44adaca0d8a6a57f7c8e7d2986d7e89fcf33526f).

**Comment by Garry050** [comment]
0.3.2.2, 0.3.2.3 still doesn't work. we need disable other graphics card or disconnect monitor

**Comment by dev7355608** [comment]
@Garry050 Do you mean by other graphics card your integrated card or another dedicated card? And, if you disabled it, changes the second monitor its brightness too or just the primary monitor (supposing disabling the other graphics card doesn't turn off the monitor)?

**Comment by p410n3** [comment]
@Garry050  pls explain why you have more than 2 GPUs? Are theydifferent? SLI? That will help

**Comment by Garry050** [comment]
(i'm so sorry if i wrong understand reply)
I have 2 monitor, 2 graphics card(GTX 1050Ti, 750Ti)
and I connect a monitor to each graphics card
<img src=https://storage.ppn.pw/cc/img/645ca6c4/g27d15672.png>
WinError 87 seems to have occurred when you have multiple GPUs and have multiple monitors
I don't think there is relation as to which GPU the display is connected to
( I tried connect all monitor to GTX 750 Ti. but still get WinError87 )




`Do you mean by other graphics card your integrated card or another dedicated card?`
Yes
`if you disable it, changes the second monitor its brightness too or just the primary monitor?`
**changes the second monitor its brightness too** and get WinError 87
`pls explain why you have more than 2 GPUs? Are they different? SLI? That will help`
different gpus. I'm using it for the output of the sub monitor(1050 Ti haven't D-Sub)

sorry my fucking bad english skill.... :(

**Comment by dev7355608** [comment]
@Garry050 I am a little confused now. If you did get the app to work without any errors, could you please tell me what exactly you did that made it work?

@alqy Do you also have a second monitor connected?

@Retardium @alqy What graphics card(s) you have? Did any of the two points I posted earlier help?

@Retardium @alqy  @Garry050 Are your graphics card drivers and Windows up to date?

**Comment by Garry050** [comment]
`@Garry050 I am a little confused now. If you did get the app to work without any errors, could you please tell me what exactly you did that made it work?`
yep
`@Retardium @alqy @Garry050 Are your graphics card drivers and Windows up to date?`
yep

It happens this bug when I _connect_ **multiple GPU** and **multiple monitors** as long as I confirm
I may not be able to provide more information.

**Comment by dev7355608** [comment]
Please try v0.3.2.4 (e023c49b1f7319c5a7973209f7b7982145f968cf).

**Comment by alqy** [comment]
@dev7355608 I have a dual monitor set up, both connected to a msi radeon r9 390. Im not sure what was different in v0.3.2.4 but i was able to get it to work this time! I appreciate the help!!

**Comment by Garry050** [comment]
it works. (if i got blind, changing brightness(? or gamma? idk) second monitor too. but it isn't big problem, anyway thx)

**Comment by dev7355608** [comment]
Glad to hear it works now.
