### ISSUE TITLE
All screens are blacked out.

### ISSUE THREAD

**Issue by Winj3** [dev7355608/csgo_dont_blind_me#6]
I have a trippel monitor setup, and when flashed all my screens go black. I use a different gpu for csgo than the one i use for my to other monitors. I have csgo in fullscreen stretched.

**Comment by Simber1** [comment]
This was mentioned in #4

**Comment by p410n3** [comment]
Yup. Make sure you use the newest version. Also pls provide an error log

**Comment by dev7355608** [comment]
Unfortunately, it seems to be not always possible to set the brightness for each monitor individually. I implemented it in a way such that it checks whether it is possible to set the brightness of the primary monitor only or not. In most cases it seems to be impossible. I think I have not seen or heard of a case where it works. I am not sure if this is a problem within Windows or GPU related limitations. Programs like f.lux or redshift also suffer from the same issue.
