### ISSUE TITLE
Is this considered a cheat?

### ISSUE THREAD

**Issue by edobrb** [dev7355608/csgo_dont_blind_me#8]
I'm asking if this can trigger a VAC ban or if this is against some rules.

**Comment by dev7355608** [comment]
It's not cheat, and it is completely legal. It just adjusts the screen brightness based on the info that is provided by the official [game state integration system](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration). It won't trigger a VAC ban.
